### ISSUE TITLE
Tell if battery level low

### ISSUE THREAD

**Issue by paha77** [awokurka/garmin-fit-battery#1]
I've run into this project while searching for information about battery levels in FIT files.

Would it be somehow tell from the reported battery level if the connected ANT+ device needs to be charged?  It'd be a very useful use case to get a warning after the ride if one of the devices needs to be charged.

**Comment by turbanist** [comment]
If the recorded Device has written the field battery_status inside the .fit file, then you'll see something else as "OK" in the Battery Status Column. It's a bit weird, as it seems to be not a common practice to submit the battery levels of a device or sensor at least once during an activity recording. So i've giving up on this, your best bet is to use your last five activities and check if the device in question has once written its battery level into the .fit file...

**Comment by paha77** [comment]
Yep, I see such information in the FIT file:

![image](https://github.com/awokurka/garmin-fit-battery/assets/5096366/2af0f85e-8a1b-45c1-aa07-f69c05236753)

But the value "OK" is not really satisfying. :)

And yes, sometimes this message (device_info) is only written once (at the beginning of the activity) and sometimes at the end too.

**Comment by turbanist** [comment]
But "ok" means it is still good to go, at least this would be my interpretation of this value. Again this is written by the device or sensor itself, so there is nothing i can do.
